{% set name = "qcfractal" %}
{% set version = "0.51" %}
# pattern for unpublished commits {% set version = "0.50b13.post52+gbb2748c85" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # unpublished - any repo commit. sync commit in git_rev below with commit and distance in version above
  #git_url: https://github.com/MolSSI/QCFractal.git
  #git_rev: bb2748c8534b267e33f894ef71a2d9a6da50c5af
  #sha256: 81cdc093dda5e7739496088b70be7c3110fb691b4fdf22c7e3b58377450e2081
  # published tags.
  - url: https://pypi.io/packages/source/q/qcportal/qcportal-{{ version }}.tar.gz
    sha256: 6d7e435f4f513680ee2f543a221deed376c8d27c8f815ca18dac7d014b41b5f5
    folder: qcportal
  - url: https://pypi.io/packages/source/q/qcfractalcompute/qcfractalcompute-{{ version }}.tar.gz
    sha256: 0e11b4b9598bbd9a5ede501d4fb84f12a30f4682b2063b17ac28186cdfdacc15
    folder: qcfractalcompute
  - url: https://pypi.io/packages/source/q/qcfractal/qcfractal-{{ version }}.tar.gz
    sha256: 2ab925dad0e502ab05f696aee048957c3f20d0fc1bcbe0347180c930b7debae2
    folder: qcfractal
  - url: https://pypi.io/packages/source/q/qcarchivetesting/qcarchivetesting-{{ version }}.tar.gz
    sha256: 60b592170cde52a422e683519ea31eb46acf28208b5f2bda21fd3037005bb7f3
    folder: qcarchivetesting

build:
  number: 0
  noarch: python

outputs:
  - name: qcportal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcportal
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >=3.8
        - numpy
        - msgpack-python
        - requests
        - pyyaml
        - pydantic >=1.10,<2.0
        - zstandard
        - qcelemental
        - tabulate
        - tqdm
        - pandas
        - pyjwt
    test:
      imports:
        - qcportal
      requires:
        - pip
        - pytest
      commands:
        - test -f $SP_DIR/qcportal/__init__.py
        - pip check
        - python -c "import qcportal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Python library for interacting with QCArchive/QCFractal servers

  - name: qcfractalcompute
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractalcompute
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >=3.8
        - qcportal ={{ version }}
        - parsl
    test:
      imports:
        - qcfractalcompute
      requires:
        - pip
        - pytest
      commands:
        - test -f $SP_DIR/qcfractalcompute/__init__.py
        - pip check
        - python -c "import qcfractalcompute as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-compute-manager --help
    about:
      summary: Distributed worker package for QCArchive

  - name: qcfractal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractal
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >=3.8
        - flask
        - flask-jwt-extended
        - gunicorn
        - bcrypt
        - sqlalchemy >=2.0
        - alembic
        - psycopg2
        - geoip2
        - torsiondrive
        - qcfractalcompute ={{ version }}
        - __unix  # [unix]
    test:
      imports:
        - qcfractal.snowflake
      requires:
        - pip
        - pytest
      commands:
        - test -f $SP_DIR/qcfractal/__init__.py
        - pip check
        - python -c "import qcfractal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-server --help
    about:
      summary: Database and Web API for the QCArchive project

  - name: qcarchivetesting
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcarchivetesting
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >=3.8
        - qcfractal ={{ version }}
        - qcengine
        - pytest
        - pytest-cov
        - codecov
    test:
      imports:
        - qcarchivetesting.helpers
      requires:
        - pip
        - pytest
      commands:
        - test -f $SP_DIR/qcarchivetesting/__init__.py
        - pip check
        - python -c "import qcarchivetesting as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Additional testing fixtures and functions for the QCArchive project

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://molssi.github.io/QCFractal/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/main/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/license/bsd-3-clause/
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
  feedstock-name: qcfractal
  recipe-maintainers:
    - lnaden
    - bennybp
