{% set name = "qcfractal" %}
{% set version = "0.12.0" %}
{% set sha256 = "78e5953420d6cc10abedd2c5ed9f529763f21870051b1e27b0841fd0ba6ed340" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
    
requirements:
  host:
    - python >=3.6
    - pip

test:
  commands:
    - echo 'Keep lint happy'

outputs:
  - name: {{ name }}-core  
    script: "python -m pip install . --no-deps --ignore-installed -vv "
    build:
        entry_points:
          - qcfractal-server = qcfractal.cli.qcfractal_server:main
          - qcfractal-manager = qcfractal.cli.qcfractal_manager:main
    requirements:
      run:
        - python >=3.6
    
        # Core dependencies
        - numpy >=1.11
        - msgpack-python >=0.6.1
        - tornado
        - requests
        - pyyaml >=5.1
        - pydantic >=1.0.0
    
        # Ecosystem dependencies
        - qcengine >=0.11.0
        - qcelemental >=0.11.0
      
        # Security dependencies
        - bcrypt
        - cryptography
      
        # Storage dependencies
        - sqlalchemy >=1.3
        - alembic
        - psycopg2 >=2.7
        - postgresql
      
        # QCPortal dependencies
        - tqdm
        - pandas
        - h5py
        - pyarrow >=0.13.0
        - double-conversion >=3.0.0

    test:
      requires:
        - pytest
        - pytest-cov
        - codecov
      imports:
        - qcfractal

  - name: {{ name }}
    requirements:
      run:
        - pin_subpackage({{ name }}-core, max_pin='x.x.x')
        - plotly >=4.0.0

  - name: {{ name }}-dashboard
    requirements:
      run:
        - pin_subpackage({{ name }}-core, max_pin='x.x.x')
        - dash >=1.4.1
        - dash_bootstrap_components >=0.7.2

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
