travis:
  secure:
    BINSTAR_TOKEN: U+31mbu6sB+SCRhNIJDUkAgiSzlm2PW7IRS/kou9yJXbP7cejQc8/MPEbVYK1+1DNQ/xvflnjecCxC4kc2bH6MxjZfKsb4jWTJ77YxsMlP4rKXOB5fksEbc01ELn47/RxDOxlzoRRKZurcT1yTJIaad6CNVqUct47+zadU0v650vlGGysWQynyzANjj3FQ2HCGTPZ/5RESZH9VSBLAV9TMcNI7LekeOeYvrx4wxPvSBCVJS8GWMwX4m2TQ37PgTCOCtnC663XIObQ1+0lu2fNI8rWd/2l9TCPcu2NtABtmuf9RbfkqvHA12b1gSvRIxJo1kJiZ/sdNmNIz09bSUU5XjEgGTQAL7XxQxS4AkyoCbye6svtFSBDiDwtn9DQ9PDZtq3VHN71uiPb4QqQrhcL9Cdls2QRPIUwDbJZXp0sSFHIAsMxLXEbZAO/ZvCL1K5ZTLD54oaFYeBtcat6nSra06TpWuITWyL1sRS3HpUy9wCuLi6Swc7vaImh+7G4yZ4AZJCMguklcVBj6xh455Y18voD0zD1qubNS8sM3IHXkN6icg75R9SNmBJW2WPYV2PehWIFoRj62orQBu/G2ktazQAL3buy+nVrhLq6tbKl/zM60w5PyHbeMq5Qh032OIIqf7+eLTTvaBnjFXW9UCKWyZyyV+Kmr9NwP7j9VDmE8E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
